unit TestCasePlainTextLog;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.Generics.Collections,
  Vcl.Dialogs, WinAPI.Windows,
  Emetra.Logging.PlainText,
  Emetra.Logging.LogItem.Interfaces,
  Emetra.Logging.PlainText.LogItem,
  Emetra.Logging.Interfaces, Vcl.Forms,

  System.StrUtils,
  System.SyncObjs,
  Vcl.Controls, IdUDPClient,
  System.Classes, System.SysUtils, System.Inifiles,
  System.Win.Registry, System.Diagnostics,
  Vcl.Graphics, Vcl.StdCtrls, System.RegularExpressions;

type
  // Test methods for class TPlainTextLog

  TestTPlainTextLog = class( TTestCase )
  strict private
    iniFile: TIniFile;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestClearTargets;
    procedure TestDecision;
    procedure TestGrayLogEvent;
    procedure TestIgnoreButton;
    procedure TestShowMessage;
  end;

implementation

uses
  Emetra.Logging.Target.Interfaces,
  Emetra.Logging.Target.Mock,
  Emetra.Logging.Target.SmartInspect,
  Emetra.Logging.Target.GrayLog;

const
  ASK_CLICK_YES_FOR_INFOLEVEL    = 'Click Yes if you see a yes/no question here with level Information (blue).';
  ASK_CLICK_NO_FOR_WARNING_LEVEL = 'Click No if you see a yes/no question here with level Warning (yellow).';
  ASK_CONFIRM_SINGLE_MESSAGE     = 'Did you see the message "%s" exactly once?';
  MSG_IGNORABLE_MESSAGE          = 'Now, listen very carefully, I shall say zis only whence.';
  MSG_VERIFY_GRAYLOG_REACHED     = '%s.%s: Verify that an entry with number %d has appeared on your GrayLog server at %s.';

const
  TXT_CLICK_IGNORE = 'Click Ignore button here!';
  TXT_CLICK_OK     = 'Click OK button here!';

const
  GRAYLOG_SERVER = '40.69.207.41';

var
  multiTarget: ILogMultitarget;

procedure TestTPlainTextLog.SetUp;
begin
  ForceDirectories( ExtractFilePath( TPlainTextLog.GetFileNameSettings ) );
  iniFile := TIniFile.Create( TPlainTextLog.GetFileNameSettings );
  iniFile.WriteString( SECTION_GRAYLOG, KEY_LOG_SERVER, EmptyStr );
end;

procedure TestTPlainTextLog.TearDown;
begin
  iniFile.Free;
end;

procedure TestTPlainTextLog.TestClearTargets;
begin
  { Make sure we have a multitarget log }
  if Supports( GlobalLog, ILogMultitarget, multiTarget ) then
  begin
    multiTarget.AddTarget( TMockTarget.Create );
    multiTarget.AddTarget( TMockTarget.Create );
    multiTarget.ClearAllTargets;
    CheckEquals( 0, multiTarget.TargetCount );
  end;
end;

procedure TestTPlainTextLog.TestDecision;
begin
  CheckTrue( GlobalLog.LogYesNo( ASK_CLICK_YES_FOR_INFOLEVEL, ltMessage ) );
  CheckFalse( GlobalLog.LogYesNo( ASK_CLICK_NO_FOR_WARNING_LEVEL, ltWarning ) );
end;

procedure TestTPlainTextLog.TestGrayLogEvent;
const
  PROC_NAME = 'TestGrayLogEvent';
begin
  Randomize( );
  Assert( Supports( GlobalLog, ILogMultitarget, multiTarget ) );
  multiTarget.ClearAllTargets;
  multiTarget.AddTarget( TGrayLogDispatcher.Create( GRAYLOG_SERVER, DEFAULT_GRAYLOG_PORT ) );
  GlobalLog.LogYesNo( Format( MSG_VERIFY_GRAYLOG_REACHED, [ClassName, PROC_NAME, Random( 10000 ), GRAYLOG_SERVER] ), ltMessage );
end;

procedure TestTPlainTextLog.TestIgnoreButton;
begin
  GlobalLog.ShowMessage( TXT_CLICK_IGNORE, ltMessage, 2 );
  CheckEquals( mrIgnore, GlobalLog.ModalResult );
  GlobalLog.ShowMessage( TXT_CLICK_OK, ltMessage, 2 );
  CheckEquals( mrOk, GlobalLog.ModalResult );
end;

procedure TestTPlainTextLog.TestShowMessage;
begin
  GlobalLog.ResetCounter( MSG_IGNORABLE_MESSAGE );
  GlobalLog.ShowMessage( MSG_IGNORABLE_MESSAGE, ltMessage, 1 );
  GlobalLog.ShowMessage( MSG_IGNORABLE_MESSAGE, ltMessage, 1 );
  GlobalLog.ShowMessage( MSG_IGNORABLE_MESSAGE, ltMessage, 2 );
  GlobalLog.ShowMessage( MSG_IGNORABLE_MESSAGE, ltMessage, 3 );
  GlobalLog.ShowMessage( MSG_IGNORABLE_MESSAGE, ltMessage, 1 );
  CheckTrue( GlobalLog.LogYesNo( Format( ASK_CONFIRM_SINGLE_MESSAGE, [MSG_IGNORABLE_MESSAGE] ) ) );
end;

initialization

if Supports( GlobalLog, ILogMultitarget, multiTarget ) then
begin
  multiTarget.ClearAllTargets;
  multiTarget.AddTarget( TGrayLogDispatcher.Create( GRAYLOG_SERVER, DEFAULT_GRAYLOG_PORT ) );
  multiTarget.AddTarget( TSmartInspectTarget.Create );
end;

// Register any test cases with the test runner
RegisterTest( TestTPlainTextLog.Suite );

end.
